input:
  file_path: data/input/sample_data.xlsx
  file_type: auto
mapping:
  file_path: mapping_column.xlsx
  sheet_name: column mapping
output:
  file_path: data/output/converted_data_multiple_rows.xlsx
  file_type: auto
processing:
  encoding: utf-8
  list_format: list_in_multiple_rows
  skip_optional_columns: false
  strict_validation: true
